### ISSUE TITLE
Divisão dos arquivos Faltantes

### ISSUE THREAD

**Issue by wdresende** [tecprog-digalandig/DigAlanDig_TecProg#5]
Dividir os arquivos entre os alunos do grupo

Critério de aceitação:

- [x] Arquivos dos alunos que trancaram divididos entre os restantes

Arquivos .h a serem divididos:

- [x] Sound.cpp
- [x] Resoucers.cpp
- [x] Component.cpp
- [x] Ligth.cpp
- [x] Music.cpp
- [x] HudCounter.cpp
- [x] HudTimer.cpp
- [x] HudMeter.cpp
- [x] InputManager.cpp 

Arquivos .cpp a serem divididos:

- [x] Sound.h
- [x] Resoucers.h
- [x] Component.h
- [x] Ligth.h
- [x] Music.h
- [x] GridControl.h
- [x] HudCount.h
- [x] HudTimer.h
- [x] HudMeter.h
- [x] InputManager.h

Cada um pega algo em torno de 2 a 3 arquivos .cpp e .h e comentar na issue quais arquivos pegou

**Comment by victoralvesgomide** [comment]
.h
Component.h
InputManager.h

.cpp
Component.cpp
InputManager.cpp

**Comment by wdresende** [comment]
.h
Light.h
HudMeter.h

.cpp
Resoucers.cpp
HudMeter.cpp

**Comment by raulvicto** [comment]
.h
HudCount.h
Music.h

.cpp
HudCounter.cpp
Music.cpp

**Comment by ingrdsoares** [comment]
.h
 Sound.h
Resources.h

.cpp
Sound.cpp

**Comment by mardntas** [comment]
.h
 GridControl.h

.cpp
Light.cpp

**Comment by matheus-rn** [comment]
.h 
HudTimer.h
.cpp
HudTimer.h
